server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${app.datasource.driver-class-name}
      url: jdbc:mysql://${app.datasource.host}:${app.datasource.port}/${app.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${app.datasource.username}
      password: ${app.datasource.password}